<?php
$ABS = array( // Ajax Browser Sentences
'language_in_English' =>  'Spanish',
'language_in_Language' => 'Espanol',
'language_abbreviation' => 'es',
'language_translator' => 'j-lz',
'language_version' => '0.2.2',
'language_src_flag' =>  'src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAALCAIAAAD5gJpuAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAFnSURBVHjaYvzPgAD/UNlYEUAAmuTYAAAQhAEYqF/zFbe50RZ1cMmS9TLi0pJLRjZohAMTGFUN9HdnHgEE1sDw//+Tp0ClINW/f0NIKPoFJH/9//ULyGaUlQXaABBALAx/Gf4zAt31F4i+ffj3/cN/XrFfzOx//v///f//LzACM/79ZmD8/e8TA0AAMYHdDVT958vXP38nMDB0s3x94/Tj5y+YahhiAKLfQKUAAcQEdtJfoDHMF2L+vPzDmFXLelf551tGFOOhev4A/QgQQExgHwAd8IdFT/Wz6j+GhlpmXSOW/2z///8Eq/sJ18Dw/zdQA0AAMQExxJjjdy9x2/76EfLz4MXdP/i+wsyGkkA3Aw3984cBIIAYfzIwMKel/bt3jwEaLNAwgZIQxp/fDH/+MqqovL14ESCAWICeZvr9h0FSEhSgwBgAygFDEMT+wwAhgQgc4kAEVAwQQIxfUSMSTxxDAECAAQAJWke8v4u1tAAAAABJRU5ErkJggg=="',

0 => '', // 'Gestionnaire de fichier via http',
1 => '', // 'Ouverture d\'une session AJAX-Browser',
	2 => 'modo', // 'Mode',
	3 => 'ultima coneccion', // 'Derniere connexion',
	4 => 'cancelar', // 'Annuler',
5 => '', // 'Login',
	6 => 'contraseña', // 'Mot de passe',
	7 => 'deconeccion', // 'Deconnexion',
	8 => 'documentacion', // 'Documentation',
	9 => 'visita n°', // 'visite n°',
	10 => 'ok', // 'OK',
	11 => 'nombre de usario', // 'Nom d\'utilisateur',
12 => '', // 'arborescence',
	13 => 'galeria', // 'gallerie',
14 => '', // 'recommandé',
	15 => 'nuevo', // 'Nouveau',
	16 => 'cortar', // 'Couper',
	17 => 'copiar', // 'Copier',
	18 => 'pegar', // 'Coller',
	19 => 'reelegir', // 'Renommer',
	20 => 'ree. una seria', // 'Ren. une serie',
	21 => 'suprimir', // 'Supprimer',
	22 => 'descargar', // 'Telecharger',
	23 => 'este mismo solamente', // 'Celui ci seulement',
	24 => 'subir', // 'Upload',
	25 => 'abrir/editar', // 'Ouvrir / Editer',
	26 => 'propriedades', // 'Proprietés',
	27 => 'desplazar aqui', // 'Deplacer ici',
	28 => 'copiar aqui', // 'Copier ici',
	29 => 'quiere esperar,cargamento en curso', // 'Veuillez patienter, chargement en cours...',
30 => '', // 'Signaler un bug et / ou faire une suggestion',
	31 => 'tamaño', // 'Taille',
	32 => 'tipo', // 'Type',
	33 => 'datos', // 'Date',
	34 => 'derechos', // 'Droits',
	35 => ' errores, estas bloqueado', // ' tentatives, Vous etes blacklisté !',
36 => '', // 'Decompresser ici',
37 => '', // 'Contribuer financierement aux ameliorations.',

// fichier ManageSuperGlobales.php
100 => 'imposible de crear un archivo', // 'Impossible de créer le fichier "*.conf" dans ".AJAX-B" veuillez verifier les droits',
	101 => 'ninguno archivo de configuracion puede encontrarse', // 'Aucun fichier de configuration n\'a été trouvé',
102 => '', // 'Veuillez definir un compte Administrateur :',
	103 => 'problema de configuracion de unas sessiones en PHP.ini, verificar que: session.use_cookies=1', // 'Probleme de configuration des session dans PHP.ini, verifier que : session.use_cookies=1',

// fichier InitHTML.php
200 => '', // 'Domaine vu sous AJAX-Browser',
	201 => 'nueva carpeta o nuevo archivo', // 'Nouveau dossier ou fichier',
	202 => 'reelegir este elemento,la seleccion o los contenidos...', // 'Renommer cet element, la selection ou les contenus...',
	203 => 'suprimir toda la seleccion', // 'Supprimer toute la selection',
	204 => 'forzar el descargamiento', // 'Forcer le Telechargement',
	205 => 'descargamiento de la seleccion al formato', // 'Telechargement de la selection au format ',
	206 => 'enviar los archivos hacia esta carpeta', // 'Deposer des fichiers vers ce repertoire.',
	207 => 'contactar el administrador del browser', // 'Contacter l\'administrateur du Browser',
208 => '', // 'Filtre le contenu visible selon le masque.',
	209 => 'extraer el vinculo hacia esta carpeta', // 'Extraire le lien vers ce dossier',
	210 => 'configurar AJAX-Browser', // 'Configurer AJAX-Browser',
	211 => 'gestion de las cuentas de usarios', // 'Gestion des comptes Utilisateurs',
	212 => 'gestion de mi profil usarios', // 'Gestion de mon profil Utilisateur',
	213 => 'a proposito de : AJAX-Browser', // 'A Propos de : AJAX-Browser',
	214 => 'gestion de las cuentas', // 'Gestion des comptes',

// fichier ExplorerTools.php
// fichier ArchiveTools.php

// fichier SessionTools.php
	300 => 'imposible de acceder e crear la carpeta de SESIONES ', // 'Impossible d\'accéder et de créer le repertoire de SESSIONS',
	301 => 'sitio official', // 'Site officiel d\'AJAX-Browser',

// fichier Command.php
	402 => 'no hay nueva version', // 'Pas de nouvelle version !',
	403 => 'espejo no esta disponible', // 'Miroir injoignable !',

// fichier Setting.php
500 => '', // 'Double Click pour choisir le dossier ouvert',
	501 => 'AJAX-Browse version', // 'AJAX-Browser Version',
	502 => 'direccion electronica del administrador', // 'E-mail de(s) l\'Administrateur(s).',
	503 => 'separar por comas', // 'Separer par des virgules.',
504 => '', // 'Serveur de mise a jour.',
	505 => 'vacio => no hay actualizacion', // 'Vide => pas de mise a jour !',
	506 => 'lo siento, espejo no disponible :-(', // 'Désolée, miroir injoignable :-(',
	507 => 'no hay actualizaciones dispinibles,tiene la ultima version ;-)', // 'Pas de mise à jour disponible,vous avez déjà la dernière version ;-)',
	508 => 'actualizacion disponible', // 'Mise à jour disponible',
	509 => 'archivo considerado como muy sensible', // 'Fichier consideré comme très peu sensible',
	510 => 'archivo considerado como sensible', // 'Fichier consideré comme sensible',
	511 => 'archivo que se puede abrir en linea con CodePress', // 'Fichier ouvrable en ligne avec CodePress',
	512 => 'carpeta por los archivos espias', // 'Dossier pour les fichiers espions',
	513 => 'registro de los archivos', // 'Enregistrement des fichiers.SPY',
514 => '', // 'Les IP.',
515 => '', // 'Les connexions.',
	516 => 'los acciones', // 'Les actions.',
	517 => 'las carpetas recorridos', // 'Les dossiers parcourus',
	518 => 'a utilizar con moderacion (gordo)', // 'A utiliser avec moderation (lourd)',
	519 => 'ver la legislacion en vigor', // 'Voir la legislation en vigueur',
520 => '', // 'Dossier pour les miniatures',
521 => '', // 'Intervale de chargement des miniatures',
522 => '', // 'Réseau local 100Mb/sec, 6000 img/min.',
523 => '', // 'Bon serveur et bonne connexion, 600 img/min.',
524 => '', // 'Serveur, connexion et images normaux, 240 img/min (recommandé)',
525 => '', // 'Serveur lent ou grosse image, 120 img/min.',
526 => '', // 'Serveur très lent ou image énorme, 40 img/min.',
527 => '', // 'Effacer les anciennes miniature.',
528 => '', // 'BlackListe.',

// fichier Account.php
	601 => 'modificar esta cuenta', // 'Modifier ce compte',
	602 => 'suprimir esta cuenta', // 'Supprimer ce compte',
	603 => 'agregar un usario', // 'Ajouter un Utilisateur',
	604 => 'direccion electronica del usario', // 'E-mail de l\'utilisateur.',
	605 => 'cambiar el codigo', // 'Changer ce code',
	606 => 'especificar un nuevo codigo', // 'Spécifier un nouveau code',
	607 => 'elegir una nueva contraseña', // 'Choisissez un nouveau mot de passe !',
	608 => 'no hay cambios', // 'Pas de changement !',
609 => '', // 'Vous pouvez le changer en cochant la case de droite',
	610 => 'configuracion de acceso', // 'Configuration d\'accés.',
611 => '', // 'Dossier par défaut à l\'ouverture',
	612 => 'recorrir las carpetas padres', // 'Parcourir les dossiers parents !',
613 => '', // 'Mode d\'affichage par défaut',
614 => '', // 'Taille des miniatures en mode gallerie',
615 => '', // 'Petite',
616 => '', // 'Moyenne',
617 => '', // 'Grande',
618 => '', // 'Enorme',
619 => '', // 'Gigantesque',
620 => '', // 'Droits sur le domaine.',
621 => '', // 'Créer des éléments',
622 => '', // 'Sera autorisé à créer des fichiers ou des dossiers',
623 => '', // 'Renommer les éléments',
624 => '', // 'Sera autorisé à renommer des fichiers ou des dossiers',
625 => '', // 'Supprimer des éléments',
626 => '', // 'Sera autorisé à supprimer des fichiers ou des dossiers',
627 => '', // 'Voir les éléments cachés',
628 => '', // 'Sera autorisé à voir les fichiers cachés (commençant par un \'.\')',
629 => '', // 'Copier des éléments',
630 => '', // 'Sera autorisé à Copier des fichiers ou des dossiers',
631 => '', // 'Déplacer des éléments',
632 => '', // 'Sera autorisé à Deplacer des fichiers ou des dossiers',
633 => '', // 'Utilisation de CodePress.',
634 => '', // 'Visu CodePress',
635 => '', // 'Edition CodePress',
636 => '', // 'Ceci est valable pour les masques définis par l\'ADMIN :',
637 => '', // 'Transfert de données.',
638 => '', // 'Peut Télécharger tout ce qui lui est accéssible !',
639 => '', // 'Upload de fichier par AJAX-Browser',
640 => '', // 'Aucun (meme pas d\'images...)',
641 => '', // 'Seulement les fichiers',
642 => '', // 'Tout sauf',
643 => '', // 'Tout, sans aucune restriction (admin)!',
644 => '', // 'Config Globale d\'administration.',
645 => '', // 'Configuration générale d\'AJAX-Browser',
646 => '', // 'Configuration de tous les comptes utilisateur',
647 => '', // 'Détail des connexions',
648 => '', // 'Obtenir d\'autres langue',
649 => '', // 'Demander d\'autres langue a l\'admin',
650 => '', // 'Décompresser des éléments',
651 => '', // 'Sera autorisé à Decompresser les elements ZIP, TAR, GZIP, BZIP2',
652 => '', // 'Retirer de la BlackListe',
653 => '', // 'Specifier un nouveau nom d utilisateur :',

// fichier ArborescenceAddon.php
// fichier Arborescence.php
// fichier GallerieAddon.php
// fichier Gallerie.php
'getFF' => '', // 'Télécharger Mozilla Firefox, afin de profiter pleinement de AJAX-Browser',

// fichier Contact.php
701 => '', // 'Votre message a été envoyé :',
702 => '', // 'Un problème s\'est produit lors de l\'envoi du message.',
703 => '', // 'Ressayez...',
704 => '', // 'Votre adresse e-mail (obligatoire)',
705 => '', // 'Titre de message (obligatoire):',
706 => '', // 'Message (obligatoire):',

// fichier ManageUpload.php
801 => '', // 'Une erreur s\'est produite sur ',
802 => '', // 'Verifier les droits d\'écriture de ',
803 => '', // 'Ce type de fichier ne vous est pas autorisé à l\'upload.',
804 => '', // 'Erreur, fichier non reçu',
805 => '', // 'Aucun fichier uploadé',

// fichiers *.JS
900 => '', // 'Erreur serveur !',
906 => '', // 'Votre navigateur n\'est pas supporté',
907 => '', // 'Vos configurations anti PopUp ne permettent pas d\'ouvrir cette fenêtre.',
908 => '', // 'Spécifiez un nom pour ce nouvel élément',
909 => '', // 'terminez par un / pour créer un dossier',
910 => '', // 'Spécifiez un nouveau nom pour la selection.',
911 => '', // 'Pour une sélection multiple vous pouvez utliser ces caractères génériques',
912 => '', // 'nom actuel',
913 => '', // 'dossier',
914 => '', // 'compteur',
915 => '', // 'sans extention',
916 => '', // 'exemple si vous entrez',
917 => '', // 'Etes vous certain de vouloir supprimer définitivement les éléments selectionnés?',
918 => '', // 'Ajouter un autre fichier',
);?>