<?php
$ABS = array( // Ajax Browser Sentences
'language_in_English' => 'French',
'language_in_Language' => 'Francais',
'language_abbreviation' => 'fr',
'language_translator' => 'solene.chatelain',
'language_version' => '0.3.2',
  'language_src_flag' => 'src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAALCAIAAAD5gJpuAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAGzSURBVHjaYiyeepkBBv79+Zfnx/f379+fP38CyT9//jAyMiq5GP77wvDnJ8MfoAIGBoAAYgGqC7STApL///3/9++/pCTv////Qdz/QO4/IMna0vf/z+9/v379//37bUUTQACBNDD8Z/j87fffvyAVX79+/Q8GQDbQeKA9fM+e/Pv18/+vnwzCIkBLAAKQOAY5AIAwCEv4/4PddNUm3ji0QJyxW3rgzE0iLfqDGr2oYuu0l54AYvnz5x9Q6d+/QPQfyAQqAin9B3EOyG1A1UDj//36zfjr1y8GBoAAFI9BDgAwCMIw+P8Ho3GDO6XQ0l4MN8b2kUwYaLszqgKM/KHcDXwBxAJUD3TJ779A8h9Q5D8SAHoARP36+Rfo41+/mcA2AAQQy49ff0Cu//MPpAeI/0FdA1QNYYNVA/3wmwEYVgwMAAHE8uPHH5BqoD1//gJJLADoJKDS378Z//wFhhJAALF8A3rizz8uTmYg788fJkj4QOKREQyYxSWBhjEC/fcXZANAALF8+/anbcHlHz9+ffvx58uPX9KckkCn/gby/wLd8uvHjx96k+cD1UGiGQgAAgwA7q17ZpsMdUQAAAAASUVORK5CYII="',

0 => 'Gestionnaire de fichier via http',
1 => 'Ouverture d´une session AJAX-Browser',
2 => 'Mode',
3 => 'Derniere connexion',
4 => 'Annuler',
5 => 'Login',
6 => 'Mot de passe',
7 => 'Deconnexion',
8 => 'Documentation',
9 => 'visite n°',
10 => 'OK',
11 => 'Nom d´utilisateur',
12 => 'arborescence',
13 => 'gallerie',
14 => 'recommandé',

15 => 'Nouveau',
16 => 'Couper',
17 => 'Copier',
18 => 'Coller',
19 => 'Renommer',
20 => 'Ren. une serie',
21 => 'Supprimer',
22 => 'Telecharger',
23 => 'Celui ci seulement',
24 => 'Upload',
25 => 'Ouvrir / Editer',
26 => 'Proprietés',
27 => 'Deplacer ici',
28 => 'Copier ici',
29 => 'Veuillez patienter, chargement en cours...',
30 => 'Signaler un bug et / ou faire une suggestion',
31 => 'Taille',
32 => 'Type',
33 => 'Date',
34 => 'Droits',
35 => ' tentatives, Vous etes blacklisté !',
36 => 'Decompresser ici',
37 => 'Contribuer ou financer.',

// fichier ManageSuperGlobales.php
100 => 'Impossible de créer le fichier ´*.conf´ dans ´.AJAX-B´ veuillez verifier les droits',
101 => 'Aucun fichier de configuration n´a été trouvé',
102 => 'Veuillez definir un compte Administrateur :',
103 => 'Probleme de configuration des session dans PHP.ini, verifier que : session.use_cookies=1',

// fichier InitHTML.php
200 => 'Domaine vu sous AJAX-Browser',
201 => 'Nouveau dossier ou fichier',
202 => 'Renommer cet element, la selection ou les contenus...',
203 => 'Supprimer toute la selection',
204 => 'Forcer le Telechargement',
205 => 'Telechargement de la selection au format ',
206 => 'Deposer des fichiers vers ce repertoire.',
207 => 'Contacter l´administrateur du Browser',
208 => 'Filtre le contenu visible selon le masque.',
209 => 'Extraire le lien vers ce dossier',
210 => 'Configurer AJAX-Browser',
211 => 'Gestion des comptes Utilisateurs',
212 => 'Gestion de mon profil Utilisateur',
213 => 'A Propos de : AJAX-Browser',
214 =>'Gestion des comptes',

// fichier ExplorerTools.php
// fichier ArchiveTools.php

// fichier SessionTools.php
300 => 'Impossible d´accéder et de créer le repertoire de SESSIONS',
301 => 'Site officiel d´AJAX-Browser',

// fichier Command.php
402 => 'Pas de nouvelle version !',
403 => 'Miroir injoignable !',

// fichier Setting.php
500 => 'Double Click pour choisir le dossier ouvert',
501 => 'AJAX-Browser Version',
502 => 'E-mail de(s) l´Administrateur(s).',
503 => 'Separer par des virgules.',
504 => 'Serveur de mise a jour.',
505 => 'Vide => pas de mise a jour !',
506 => 'Désolée, miroir injoignable :-(',
507 => 'Pas de mise à jour disponible,vous avez déjà la dernière version ;-)',
508 => 'Mise à jour disponible',
509 => 'Fichier consideré comme très peu sensible',
510 => 'Fichier consideré comme sensible',
511 => 'Fichier ouvrable en ligne avec CodePress',
512 => 'Dossier pour les fichiers espions',
513 => 'Enregistrement des fichiers.SPY',
514 => 'Les IP.',
515 => 'Les connexions.',
516 => 'Les actions.',
517 => 'Les dossiers parcourus',
518 => 'A utiliser avec moderation (lourd)',
519 => 'Voir la legislation en vigueur',
520 => 'Dossier pour les miniatures',
521 => 'Intervale de chargement des miniatures',
522 => 'Réseau local 100Mb/sec, 6000 img/min.',
523 => 'Bon serveur et bonne connexion, 600 img/min.',
524 => 'Serveur, connexion et images normaux, 240 img/min (recommandé)',
525 => 'Serveur lent ou grosse image, 120 img/min.',
526 => 'Serveur très lent ou image énorme, 40 img/min.',
527 => 'Effacer les anciennes miniature.',
528 => 'BlackListe.',

// fichier Account.php
601 => 'Modifier ce compte',
602 => 'Supprimer ce compte',
603 => 'Ajouter un Utilisateur',
604 => 'E-mail de l´utilisateur.',
605 => 'Changer ce code',
606 => 'Spécifier un nouveau code',
607 => 'Choisissez un nouveau mot de passe !',
608 => 'Pas de changement !',
609 => 'Vous pouvez le changer en cochant la case de droite',
610 => 'Configuration d´accés.',
611 => 'Dossier par défaut à l´ouverture',
612 => 'Parcourir les dossiers parents !',
613 => 'Mode d´affichage par défaut',
614 => 'Taille des miniatures en mode gallerie',
615 => 'Petite',
616 => 'Moyenne',
617 => 'Grande',
618 => 'Enorme',
619 => 'Gigantesque',
620 => 'Droits sur le domaine.',
621 => 'Créer des éléments',
622 => 'Sera autorisé à créer des fichiers ou des dossiers',
623 => 'Renommer les éléments',
624 => 'Sera autorisé à renommer des fichiers ou des dossiers',
625 => 'Supprimer des éléments',
626 => 'Sera autorisé à supprimer des fichiers ou des dossiers',
627 => 'Voir les éléments cachés',
628 => 'Sera autorisé à voir les fichiers cachés (commençant par un ´.´)',
629 => 'Copier des éléments',
630 => 'Sera autorisé à Copier des fichiers ou des dossiers',
631 => 'Déplacer des éléments',
632 => 'Sera autorisé à Deplacer des fichiers ou des dossiers',
633 => 'Utilisation de CodePress.',
634 => 'Visu CodePress',
635 => 'Edition CodePress',
636 => 'Ceci est valable pour les masques définis par l´ADMIN :',
637 => 'Transfert de données.',
638 => 'Peut Télécharger tout ce qui lui est accéssible !',
639 => 'Upload de fichier par AJAX-Browser',
640 => 'Aucun (meme pas d´images...)',
641 => 'Seulement les fichiers',
642 => 'Tout sauf',
643 => 'Tout, sans aucune restriction (admin)!',
644 => 'Config Globale d´administration.',
645 => 'Configuration générale d´AJAX-Browser',
646 => 'Configuration de tous les comptes utilisateur',
647 => 'Détail des connexions',
648 => 'Obtenir d´autres langue',
649 => 'Demander d´autres langue a l´admin',
650 => 'Décompresser des éléments',
651 => 'Sera autorisé à Decompresser les elements ZIP, TAR, GZIP, BZIP2',
652 => 'Retirer de la BlackListe',
653 => 'Specifier un nouveau nom d utilisateur :',

// fichier ArborescenceAddon.php
// fichier Arborescence.php
// fichier GallerieAddon.php
// fichier Gallerie.php
'getFF' => 'Télécharger Mozilla Firefox, afin de profiter pleinement de AJAX-Browser',

// fichier Contact.php
701 => 'Votre message a été envoyé :',
702 => 'Un problème s´est produit lors de l´envoi du message.',
703 => 'Ressayez...',
704 => 'Votre adresse e-mail (obligatoire)',
705 => 'Titre de message (obligatoire):',
706 => 'Message (obligatoire):',

// fichier ManageUpload.php
801 => 'Une erreur s´est produite sur ',
802 => 'Verifier les droits d´écriture de ',
803 => 'Ce type de fichier ne vous est pas autorisé à l´upload.',
804 => 'Erreur, fichier non reçu',
805 => 'Aucun fichier uploadé',

// fichiers *.JS
900 => 'Erreur serveur !',
906 => 'Votre navigateur n´est pas supporté',
907 => 'Vos configurations anti PopUp ne permettent pas d´ouvrir cette fenêtre.',
908 => 'Spécifiez un nom pour ce nouvel élément',
909 => 'terminez par un / pour créer un dossier',
910 => 'Spécifiez un nouveau nom pour la selection.',
911 => 'Pour une sélection multiple vous pouvez utliser ces caractères génériques',
912 => 'nom actuel',
913 => 'dossier',
914 => 'compteur',
915 => 'sans extention',
916 => 'exemple si vous entrez',
917 => 'Etes vous certain de vouloir supprimer définitivement les éléments selectionnés?',
918 => 'Ajouter un autre fichier',
);?>