<?php
$ABS = array( // Ajax Browser Sentences
'language_in_English' => 'English',
'language_in_Language' => 'English',
'language_abbreviation' => 'en',
'language_translator' => 'solene.chatelain, francois.felix, atlan_d',
'language_version' => '0.3.2',
'language_src_flag' => 'src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAALCAIAAAD5gJpuAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAflJREFUeNpinDRzn5qN3uFDt16+YWBg+Pv339+KGN0rbVP+//2rW5tf0Hfy/2+mr99+yKpyOl3Ydt8njEWIn8f9zj639NC7j78eP//8739GVUUhNUNuhl8//ysKeZrJ/v7z10Zb2PTQTIY1XZO2Xmfad+f7XgkXxuUrVB6cjPVXef78JyMjA8PFuwyX7gAZj97+T2e9o3d4BWNp84K1NzubTjAB3fH0+fv6N3qP/ir9bW6ozNQCijB8/8zw/TuQ7r4/ndvN5mZgkpPXiis3Pv34+ZPh5t23//79Rwehof/9/NDEgMrOXHvJcrllgpoRN8PFOwy/fzP8+gUlgZI/f/5xcPj/69e/37//AUX+/mXRkN555gsOG2xt/5hZQMwF4r9///75++f3nz8nr75gSms82jfvQnT6zqvXPjC8e/srJQHo9P9fvwNtAHmG4f8zZ6dDc3bIyM2LTNlsbtfM9OPHH3FhtqUz3eXX9H+cOy9ZMB2o6t/Pn0DHMPz/b+2wXGTvPlPGFxdcD+mZyjP8+8MUE6sa7a/xo6Pykn1s4zdzIZ6///8zMGpKM2pKAB0jqy4UE7/msKat6Jw5mafrsxNtWZ6/fjvNLW29qv25pQd///n+5+/fxDDVbcc//P/zx/36m5Ub9zL8+7t66yEROcHK7q5bldMBAgwADcRBCuVLfoEAAAAASUVORK5CYII="',

0 => 'HTTP File Manager',
1 => 'Log in to AJAX-Browser',
2 => 'Mode',
3 => 'Last login',
4 => 'Cancel',
5 => 'Login',
6 => 'Password',
7 => 'Sign out',
8 => 'Help',
9 => 'Visit',
10 => 'OK',
11 => 'Username',
12 => 'Tree view',
13 => 'Gallery',
14 => 'Recommended',

15 => 'New',
16 => 'Cut',
17 => 'Copy',
18 => 'Paste',
19 => 'Rename',
20 => 'Multi rename',
21 => 'Delete',
22 => 'Download',
23 => 'This file only',
24 => 'Upload',
25 => 'Open / Edit',
26 => 'Properties',
27 => 'Move here',
28 => 'Copy here',
29 => 'Please wait, loading...',
30 => 'Report a bug and/or send a comment',
31 => 'Size',
32 => 'Type',
33 => 'Date',
34 => 'Rights',
35 => ' trials, You are Blacklisted !',
36 => 'Uncompress here',
37 => 'Contribuer financierement aux ameliorations.',

// fichier ManageSuperGlobales.php
100 => 'Cannot create file "*.conf" in "AJAX-B", please check access rights',
101 => 'Setting file not found',
102 => 'Please create an admin account:',
103 => '?', // Probleme de configuration des session dans PHP.ini, verifier que : session.use_cookies=1',

// fichier InitHTML.php
200 => 'Website powered by AJAX-Browser application',
201 => 'New file or folder',
202 => 'Rename this item, selection or contents...',
203 => 'Delete selection',
204 => 'Force download',
205 => 'Download selection to format',
206 => 'Upload files to this folder',
207 => 'Contact Browser Admin',
208 => 'Apply mask to visible contents',
209 => 'Send link to this folder',
210 => 'AJAX-Browser settings',
211 => 'User Accounts management',
212 => 'My User Profile management',
213 => 'About : AJAX-Browser',
214 =>'Manage accounts',

// fichier ExplorerTools.php
// fichier ArchiveTools.php

// fichier SessionTools.php
300 => 'Cannot access and create the SESSIONS directory',
301 => 'AJAX-Browser official website',

// fichier Command.php
402 => 'No update available!',
403 => 'Mirror unreachable!',

// fichier Setting.php
500 => 'Double-click to open folder',
501 => 'AJAX-Browser Version',
502 => 'Admin(s) email address.',
503 => 'Separate with commas',
504 => 'Update Mirror.',
505 => 'Empty => no update !',
506 => 'Sorry, mirror unreachable :-(',
507 => 'No update available, you already have the latest version installed ;-)',
508 => 'Update available',
509 => 'Files considered non sensitive',
510 => 'Files considered sensitive',
511 => 'File to be opened online with CodePress',
512 => 'Folder for *.spy files',
513 => 'Saving SPY files',
514 => 'IP.',
515 => 'Logins.',
516 => 'Actions.',
517 => 'Read folders',
518 => 'Warning: use with caution',
519 => 'See applicable law',
520 => 'Folder thumbnail',
521 => 'Thumbnail loading lead time',
522 => 'Network 100Mb/sec, 6000 pics/min.',
523 => 'Good server and connection, 600 pics/min.',
524 => 'Normal server, connection and pictures, 240 pics/min (recommended)',
525 => 'Slow serveur or big picture, 120 pics/min.',
526 => 'Very slow server or huge picture, 40 pics/min.',
527 => 'Erase the old thumbnails.',
528 => 'BlackList.',

// fichier Account.php
601 => 'Change this account',
602 => 'Delete this account',
603 => 'Add a user',
604 => 'User email address.',
605 => 'Change password',
606 => 'Set a new password',
607 => 'Select a new password !',
608 => 'No change !',
609 => 'You may change it by ticking the box on the right',
610 => 'Access settings',
611 => 'Default folder on startup',
612 => 'Browse parent folders!',
613 => 'Default display mode',
614 => 'Thumbnail size in Gallery mode',
615 => 'Small',
616 => 'Medium',
617 => 'Big',
618 => 'Huge',
619 => 'Bleeding massive',
620 => 'Rights on the domain',
621 => 'Create items',
622 => 'Will be allowed to create files or folders',
623 => 'Rename items',
624 => 'Will be allowed to rename files or folders',
625 => 'Delete items',
626 => 'Will be allowed to delete files or folders',
627 => 'See hidden files',
628 => 'Will be allowed  to see hidden files (starting with ´.´)',
629 => 'Copy items',
630 => 'Will be authorized to copy files or folders',
631 => 'Move items',
632 => 'Will be authorized to move files or folders',
633 => 'Use CodePress.',
634 => 'CodePress view',
635 => 'CodePress edition',
636 => 'This applies to masks defined by the Admin',
637 => 'Data transfer',
638 => 'Can download anything accessible',
639 => 'Upload file with AJAX-Browser',
640 => 'None (not even a picture...)',
641 => 'Files only',
642 => 'Everything but',
643 => 'Everything, with no restriction (admin)!',
644 => 'Global Management settings',
645 => 'AJAX-Browser general settings',
646 => 'Setup all user accounts',
647 => 'Connection details',
648 => 'Get more languages',
649 => 'Request more languages',
650 => 'Uncompress items',
651 => 'Will be allowed to decompress ZIP, TAR, GZIP, BZIP2',
652 => 'Remove from BlackList',
653 => 'Setup new username :',

// fichier ArborescenceAddon.php
// fichier Arborescence.php
// fichier GallerieAddon.php
// fichier Gallerie.php
'getFF' => 'Download Mowilla Firefox and get the best from AJAX-Browser',

// fichier Contact.php
701 => 'Your message was sent:',
702 => 'A problem occured while sending the message',
703 => 'Try again...',
704 => 'Your e-mail address (required)',
705 => 'Message subject  (required):',
706 => 'Message (required):',

// fichier ManageUpload.php
801 => 'An error occured on ',
802 => 'Check write access rights on ',
803 => 'You are not allowed to upload this type of file',
804 => 'Error, file not received',
805 => 'No file uploaded',

// fichiers *.JS
900 => 'Server error!',
906 => 'Your browser is not supported',
907 => 'Your pop-up blocking does not allow to open this window',
908 => 'Please enter a name for this new item',
909 => 'End with a / to create a new folder',
910 => 'Please enter a new name for the selection.',
911 => 'You can use wildcards for multiple selection',
912 => 'current name',
913 => 'folder',
914 => 'counter',
915 => 'no extention',
916 => 'example: ',
917 => 'Do you really want to permanently delete the selected items?',
918 => 'Add another file',
);?>